### ISSUE TITLE
S3 putObject issue with javax.net.ssl.SSLException=

### ISSUE THREAD

**Issue by quangtrung89** [awslabs/aws-sdk-android-samples#34] opened 2015-11-04 16:04 UTC
Hi,

I tried to uploaded image to S3 with SDK 2.2.7. And I got this exception, instead the file uploaded is successful. Do you have any ideas?

javax.net.ssl.SSLException: Write error: ssl=0x5df4b3c8: I/O error during system call, Broken pipe
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_write(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:693)
at libcore.net.http.FixedLengthOutputStream.write(FixedLengthOutputStream.java:41)
at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1618)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1433)

Thanks!

**Comment by wdane** [comment] 2015-11-04 19:23
What Android version is this running on?  Are you on a solid connection, and is the error consistent? Is this exception being logged or actually thrown?

**Comment by quangtrung89** [comment] 2015-11-05 09:02
I am using Android version 4.4 (19). 

    public static void upLoadImageToAmazonS3(final Bitmap bitmap, final CKIS3Authentication authentication, final Context context){
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
//                    File imgFile = scaleImage(filePath, context);
                    File imgFile = scaleImage(bitmap, context);
                    BasicSessionCredentials credentials = new BasicSessionCredentials(authentication.credentials.AccessKeyId, authentication.credentials.SecretAccessKey, authentication.credentials.SessionToken);
                    AmazonS3Client s3Client = new AmazonS3Client(credentials);
                    s3Client.putObject(authentication.getBucketName(), authentication.getKey(), imgFile);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        thread.start();
    }

Exception being logged, is function caused exception
                    s3Client.putObject(authentication.getBucketName(), authentication.getKey(), imgFile);
Thanks,

**Comment by quangtrung89** [comment] 2015-11-09 15:34
Hello guys? Any ideas?

**Comment by fosterzhang** [comment] 2015-11-09 22:36
@quangtrung89 sorry for the late reply. Is your on Wifi or cellular data? Does the same error occur on emulator which usually has more stable internet connection?

**Comment by quangtrung89** [comment] 2015-11-10 05:58
Hi, I got same error on both Wifi or cellular data. And same with emulator.

Ah one more information. The first time upload file there is no issue, I just got exception from the second time. And file still successful uploaded to S3.

Thanks.

**Comment by fosterzhang** [comment] 2015-11-10 06:33
@quangtrung89 the reason I asked about the connection is to figure out whether it's caused by switching internet connection between Wifi and cellular. Would you provide as much information as possible to reproduce the problem?
- version of emulator
- region of S3, example bucket name and object name
- where you connect S3 from, Asia, US?

**Comment by quangtrung89** [comment] 2015-11-10 08:14
Hi,

* version of emulator: Nexus_S_API_19
* region of S3 Europe and  bucket name: clubkicker-user-data
* Connect S3 from Finland.

Thanks.

**Comment by fosterzhang** [comment] 2015-11-10 09:06
@quangtrung89 
- I assume Nexus_S_API_19 an API level 19 image.
- Is S3 Europe EU (Ireland eu-west-1) or EU (Frankfurt eu-central-1)?

**Comment by quangtrung89** [comment] 2015-11-10 09:23
* Yes, API level 19 image
* S3 Europe EU (Ireland eu-west-1).

**Comment by fosterzhang** [comment] 2015-11-10 19:55
I couldn't reproduce the problem on emulator API level 19. I uploaded files with similar bucket name and object name to S3 in EU Ireland eu-west-1. The only difference is I am in US.

I noticed you didn't set the correct region to s3Client. It'll cause a redirect from the standard region us-east-1 to eu-west-1 which can be slow given you want to upload a file. It's recommended to set the region if you know it.
```java
AmazonS3Client s3Client = new AmazonS3Client(credentials);
s3Client.setRegion(Region.getRegion(Regions.EU_WEST_1));
```

**Comment by quangtrung89** [comment] 2015-11-12 09:15
After setRegion I didn't get exception for Emulator any more. But still get error with devices :(. Really weird case.

**Comment by fosterzhang** [comment] 2015-11-12 20:41
@quangtrung89 which device?

**Comment by quangtrung89** [comment] 2015-11-16 08:35
Samsung Galaxy S3 (GT--I9305 Android 4.1.2 API 16), and Samsung Galaxy S4 mini (GT- I9190 Android 4.4.1 API 19).

**Comment by quangtrung89** [comment] 2015-11-23 05:38
@fosterzhang Sorry any helps on this issue?

**Comment by fosterzhang** [comment] 2015-11-25 17:44
@quangtrung89 I don't have those devices and I can't reproduce the problem on emulator. I suspect it's something related to the network because emulator usually has better network. A few things to try in order to narrow down the cause:
- try the same code in other S3 regions.
- try to upload small objects, say less 200k.
- force your device on either Wifi or cellular but not both.

**Comment by quangtrung89** [comment] 2015-11-27 23:35
Thanks, I will try and let u know!

**Comment by fosterzhang** [comment] 2016-01-29 01:25
Closing this. Feel free to reopen it if the issue persists.

**Closed by fosterzhang** 2016-01-29 01:25 UTC
Labels: question
