### ISSUE TITLE
Error during S3 Upload

### ISSUE THREAD

**Issue by ckarthikv** [awslabs/aws-sdk-android-samples#36] opened 2015-12-08 14:43 UTC
While uploading a file or image to an S3 bucket using Transfer Utility, I'm getting the error below. Previously, I used to use Transfer Manager. Please advice.

*UploadActivity﹕ Error during upload: 8
    java.lang.IllegalStateException: Transfer failed. at com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver$TransferContentObserver.onChange(TransferObserver.java:219)
            at android.database.ContentObserver.onChange(ContentObserver.java:130)
            at android.database.ContentObserver.onChange(ContentObserver.java:145)
            at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5290)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)*

**Comment by ckarthikv** [comment] 2015-12-08 15:42
On further inspection, I found this log. Any leads? - 
I/AmazonHttpClient﹕ Unable to execute HTTP request: Write error: ssl=0x7f9b525980: I/O error during system call, Connection reset by peer
    javax.net.ssl.SSLException: Write error: ssl=0x7f9b525980: I/O error during system call, Connection reset by peer
            at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
            at com.android.okio.Okio$1.write(Okio.java:70)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
            at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
            at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
            at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1618)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:174)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:74)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:40)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by fosterzhang** [comment] 2015-12-08 19:53
@ckarthikv Would you please provide the following information?
- version of the AWS SDK for Android. The latest one is 2.2.9.
- what device/emulator do you run the sample on? Model, make and Android version.
- is your device on Wifi or cellular?
- which does the s3 bucket live in, say us-east-1, eu-west-1, etc?
- code snippet to reproduce the problem

**Comment by ckarthikv** [comment] 2015-12-09 05:17
@fosterzhang -
- Yes, I'm using the latest one - 2.2.9
- I'm running the app directly on a OnePlusTwo. Android 5.1.1 on Oxygen OS 2.1.1
- Both - Connects to Wifi if WiFi is there, and if not, shifts to cellular. Tried on both, same issue.
- s3 bucket is in us-east-1
- I just ran the exact s3 sample in this project without modifying anything except the constants (s3 bucket name and Cognito Pool ID). I can upload successfully using Transfer Manager already (for the same s3 bucket, cognito pool ID and same phone), and wanted to move to Transfer Utility but couldn't run the sample app to test it.

**Comment by fosterzhang** [comment] 2015-12-09 19:34
@ckarthikv Interesting. For TransferManager, do you use the same version of SDK? Does the bucket name have special characters like dot, hyphen or underscore?

**Comment by ckarthikv** [comment] 2015-12-09 21:04
Transfer manager is slightly older version, and yes the bucket name has a
dot in it. Any suggestions?

On Thu, Dec 10, 2015, 1:04 AM Yangfan Zhang <notifications@github.com>
wrote:

> @ckarthikv <https://github.com/ckarthikv> Interesting. For
> TransferManager, do you use the same version of SDK? Does the bucket name
> have special characters like dot, hyphen or underscore?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-android-samples/issues/36#issuecomment-163366767>
> .
>
-- 

Karthik Vaidyanath

**Comment by fosterzhang** [comment] 2015-12-09 21:42
I still can't reproduce the problem. FYI, since v2.2.0, the HTTP code of the SDK has been rewritten to switch from Apache to HttpURLConnection, as suggested by Android. We did lots of testing for the transition. We expect slightly different behaviors, but not the error your encountered.

To narrow down the problem, would you please try the following
- run the sample on a different device
- run the sample on an emulator
- run the TransferManager sample. You can find it in earlier commit, say 3f3b96bd79557af1135e88fa9d0c21b7178b8993
- write a sample app that does the upload with AmazonS3.putObject()

**Comment by fosterzhang** [comment] 2016-01-29 01:26
Closing this. Feel free to reopen it if the issue persists.

**Closed** 2016-01-29 01:27 UTC
Labels: question
