### ISSUE TITLE
Amazon S3 Transfer utility Pause-Resume got Wrong image

### ISSUE THREAD

**Issue by jitendraramoliya** [awslabs/aws-sdk-android-samples#33] opened 2015-10-19 07:16 UTC
I am trying to download image from amazon using Amazon S3 Transfer utility. I have done pause and resume many times while download image. So got image merged 2-3 peice of single image into wrong new image. Could anyone provide me solution on this? Why I am getting this problem.

**Comment by fosterzhang** [comment] 2015-10-19 19:35
duplicate of https://github.com/aws/aws-sdk-android/issues/66

**Closed by fosterzhang** 2015-10-19 19:35 UTC
Labels: duplicate
