### ISSUE TITLE
Unable to execute HTTP request: null

### ISSUE THREAD

**Issue by livrish** [awslabs/aws-sdk-android-samples#40] opened 2016-01-15 06:44 UTC
Hi 
if I execute the following with a bit of a "little" delay I get   Unable to execute HTTP request: null it still works .... if I execute more than once quickly it doesn't do this
Thanks 

      CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                context, // Context
                "us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // Identity Pool ID
                Regions.US_EAST_1 // Region
        );
        
        String token = credentialsProvider.getToken();

01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient: Unable to execute HTTP request: null
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient: java.io.EOFException
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.io.Streams.readAsciiLine(Streams.java:203)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:560)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:813)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.net.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:482)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at libcore.net.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:139)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:879)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:499)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.cognito.sync.demo.AWSSignerBase.reporterror(AWSSignerBase.java:223)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.amazonaws.cognito.sync.demo.MainActivity$1.onClick(MainActivity.java:116)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.view.View.performClick(View.java:4084)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.view.View$PerformClick.run(View.java:16966)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.os.Handler.handleCallback(Handler.java:615)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.os.Handler.dispatchMessage(Handler.java:92)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.os.Looper.loop(Looper.java:137)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at android.app.ActivityThread.main(ActivityThread.java:4745)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at java.lang.reflect.Method.invokeNative(Native Method)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at java.lang.reflect.Method.invoke(Method.java:511)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-15 06:42:01.053 29104-29104/com.amazonaws.cognito.sync.demo I/AmazonHttpClient:     at dalvik.system.NativeStart.main(Native Method)

**Comment by fosterzhang** [comment] 2016-01-29 19:08
I can't reproduce the problem. Would you please provide the following information:
- Device/emulator information. What's the make of the device. What Android version is it running.
- AWS Android SDK version. The latest version is v2.2.11.
- Code snippet to reduce the problem.

**Comment by fosterzhang** [comment] 2016-02-26 20:49
Closing this as it's lack of information. Feel free to reopen it.

**Closed** 2016-03-01 05:23 UTC
Labels: question
